- hosts: localhost
  #connection: local
  gather_facts: False
  tasks:
    - shell: whoami
      register: result
    - debug: var=result

    - shell: whoami
      register: result
      remote_user: root
    - debug: var=result
